name: chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  get_cli: ^1.8.4
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  dash_chat_2: ^0.0.20
  firebase_analytics: ^10.8.9
  image_picker: ^1.0.8
  path: ^1.8.3
  cached_network_image: ^3.3.1
  file_picker: ^5.3.1
  url_launcher: ^6.3.0
  http: ^0.13.6
  flutter_pdfview: ^1.3.2
  open_filex: ^4.4.0
  share_plus: ^7.2.2
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

