// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZW9WYQgqo6djKMJ4W4hTg30BYMj148N4',
    appId: '1:958987182606:web:a2c855625573d0ec53125f',
    messagingSenderId: '958987182606',
    projectId: 'flutter-chat-app-88d60',
    authDomain: 'flutter-chat-app-88d60.firebaseapp.com',
    storageBucket: 'flutter-chat-app-88d60.appspot.com',
    measurementId: 'G-CNELHK6Z94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEGOP-NijTtfGJ5cKkUT-2IoO6q_dwUVQ',
    appId: '1:958987182606:android:31ee764e6af9be0853125f',
    messagingSenderId: '958987182606',
    projectId: 'flutter-chat-app-88d60',
    storageBucket: 'flutter-chat-app-88d60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3n9WqWH5Xwq3iVU0PeUb_BjWO8i5qsN8',
    appId: '1:958987182606:ios:cd73e3969401e4cd53125f',
    messagingSenderId: '958987182606',
    projectId: 'flutter-chat-app-88d60',
    storageBucket: 'flutter-chat-app-88d60.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3n9WqWH5Xwq3iVU0PeUb_BjWO8i5qsN8',
    appId: '1:958987182606:ios:cd73e3969401e4cd53125f',
    messagingSenderId: '958987182606',
    projectId: 'flutter-chat-app-88d60',
    storageBucket: 'flutter-chat-app-88d60.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZW9WYQgqo6djKMJ4W4hTg30BYMj148N4',
    appId: '1:958987182606:web:e53c8cc9ccde451053125f',
    messagingSenderId: '958987182606',
    projectId: 'flutter-chat-app-88d60',
    authDomain: 'flutter-chat-app-88d60.firebaseapp.com',
    storageBucket: 'flutter-chat-app-88d60.appspot.com',
    measurementId: 'G-MHY9BLNDJ6',
  );
}
